-- create_sigma_raw_promo_order_tables.sql
--
-- SB-CC-BLOOM-031 A1 / SB-AUD-PROMO-001 section 8.5 item 2 (2026-09-21, Pieter: "test roosville").
-- THE MIRROR RULE (Pieter ruling 21-09-2026, NORTH_STAR v1.9, SIGMA-SERVER-SCHEMA-MAP v1.7): a Sigma table
-- comes across with EVERY column, not the ones today's query needs. These six raw tables are generated
-- from the June crawl (sigma-extractor/sigma_discovery_20260603.txt), column for column: Sigma names
-- lower-cased, '%' written as '_pct', types char/varchar -> text, float -> double precision, date -> date,
-- time -> time, bit -> boolean, ints as ints. Keys are Sigma's own clustered primary keys, prefixed with
-- client_id and store_code. IntellistoX holds only current promotions, so it is a nightly SNAPSHOT keyed
-- on capture_date as well.
--
-- Loaded, for now, ONLY by scripts/Test-ExtractPromoOrderTables.ps1, run by hand on one server. The
-- nightly extractor does not read or write these tables until Pieter signs the test off.
-- RLS on, no policies, nothing granted to anon or authenticated: the extractor's service role writes,
-- readers come through SECURITY DEFINER functions (the PUBLIC-grant trap, memory 2026-09-14).
-- last_seen_at is stamped by public.sigma_stamp_last_seen() (ENG-189), so a row Sigma deletes can later
-- be told from one it still holds.

CREATE TABLE IF NOT EXISTS public.sigma_raw_dbadik (
  client_id text NOT NULL DEFAULT 'socialbrand',
  store_code text NOT NULL,
  simktnr smallint NOT NULL,
  laktnr integer NOT NULL,
  caktart text,
  dtdatvon date,
  dtdatbis date,
  dtdatfall date,
  chinw text,
  sibearb smallint,
  cbezkdkz1 text,
  cbezkdkz2 text,
  cbezkdkz3 text,
  cbezkdkz4 text,
  cbezkdkz5 text,
  cbezkdkz6 text,
  cbezkdkz7 text,
  cbezkdkz8 text,
  cbezkdkz9 text,
  cbezkdkz10 text,
  ckdnbez text,
  dterstlief date,
  sigrpwechsel smallint,
  cvorart text,
  cherk text,
  szentaktnr text,
  sifolgenr smallint,
  sizentversion smallint,
  sbemerkung text,
  extracted_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  PRIMARY KEY (client_id, store_code, simktnr, laktnr)
);
COMMENT ON TABLE public.sigma_raw_dbadik IS 'Raw mirror of Sigma dw220sdb.DBAdik, every column (27), THE MIRROR RULE (SIGMA-SERVER-SCHEMA-MAP v1.7). Key = Sigma primary key. Loaded by Test-ExtractPromoOrderTables.ps1 until signed off.';
ALTER TABLE public.sigma_raw_dbadik ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sigma_raw_dbadik FROM PUBLIC, anon, authenticated;
CREATE TRIGGER sigma_raw_dbadik_last_seen BEFORE INSERT OR UPDATE ON public.sigma_raw_dbadik FOR EACH ROW EXECUTE FUNCTION public.sigma_stamp_last_seen();

CREATE TABLE IF NOT EXISTS public.sigma_raw_dbadip (
  client_id text NOT NULL DEFAULT 'socialbrand',
  store_code text NOT NULL,
  simarkt smallint NOT NULL,
  laktnr integer NOT NULL,
  dartnr double precision NOT NULL,
  llftnr integer NOT NULL,
  clftartnr text,
  sibeh smallint NOT NULL,
  dvkakt double precision,
  dekakt double precision,
  cdispoart text,
  czusttxt text,
  dgvorbe double precision,
  sikzmae smallint,
  dbemg1 double precision,
  dbemg2 double precision,
  dbemg3 double precision,
  dbemg4 double precision,
  dbemg5 double precision,
  dbemg6 double precision,
  dbemg7 double precision,
  dbemg8 double precision,
  dbemg9 double precision,
  dbemg10 double precision,
  dbemg11 double precision,
  dbemg12 double precision,
  dbemg13 double precision,
  dbemg14 double precision,
  dbemg15 double precision,
  dbemg16 double precision,
  dbemg17 double precision,
  dbemg18 double precision,
  dbemg19 double precision,
  dbemg20 double precision,
  dtlieftag1 date,
  dtlieftag2 date,
  dtlieftag3 date,
  dtlieftag4 date,
  dtlieftag5 date,
  dtlieftag6 date,
  dtlieftag7 date,
  dtlieftag8 date,
  dtlieftag9 date,
  dtlieftag10 date,
  dtlieftag11 date,
  dtlieftag12 date,
  dtlieftag13 date,
  dtlieftag14 date,
  dtlieftag15 date,
  dtlieftag16 date,
  dtlieftag17 date,
  dtlieftag18 date,
  dtlieftag19 date,
  dtlieftag20 date,
  dvknorm double precision,
  dmenge double precision,
  ckennz text,
  ckdkz1 text,
  ckdkz2 text,
  ckdkz3 text,
  ckdkz4 text,
  ckdkz5 text,
  ckdkz6 text,
  ckdkz7 text,
  ckdkz8 text,
  ckdkz9 text,
  ckdkz10 text,
  lfolgnr integer,
  drefnr double precision,
  labteilung integer,
  lwgrp integer,
  cbez text,
  ssortfeld text,
  ssortbez text,
  cherk text,
  ckzvera text,
  dprevbemg1 double precision,
  dprevbemg2 double precision,
  dprevbemg3 double precision,
  dprevbemg4 double precision,
  dprevbemg5 double precision,
  dprevbemg6 double precision,
  dprevbemg7 double precision,
  dprevbemg8 double precision,
  dprevbemg9 double precision,
  dprevbemg10 double precision,
  dprevbemg11 double precision,
  dprevbemg12 double precision,
  dprevbemg13 double precision,
  dprevbemg14 double precision,
  dprevbemg15 double precision,
  dprevbemg16 double precision,
  dprevbemg17 double precision,
  dprevbemg18 double precision,
  dprevbemg19 double precision,
  dprevbemg20 double precision,
  dprevmenge double precision,
  dzentrzptnr double precision,
  dmngpalette double precision,
  dzuschuss double precision,
  cofferid text,
  extracted_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  PRIMARY KEY (client_id, store_code, simarkt, laktnr, dartnr, llftnr, sibeh)
);
COMMENT ON TABLE public.sigma_raw_dbadip IS 'Raw mirror of Sigma dw220sdb.DBAdip, every column (99), THE MIRROR RULE (SIGMA-SERVER-SCHEMA-MAP v1.7). Key = Sigma primary key. Loaded by Test-ExtractPromoOrderTables.ps1 until signed off.';
ALTER TABLE public.sigma_raw_dbadip ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sigma_raw_dbadip FROM PUBLIC, anon, authenticated;
CREATE TRIGGER sigma_raw_dbadip_last_seen BEFORE INSERT OR UPDATE ON public.sigma_raw_dbadip FOR EACH ROW EXECUTE FUNCTION public.sigma_stamp_last_seen();

CREATE TABLE IF NOT EXISTS public.sigma_raw_dbadit (
  client_id text NOT NULL DEFAULT 'socialbrand',
  store_code text NOT NULL,
  simarkt smallint NOT NULL,
  laktnr integer NOT NULL,
  dartnr double precision NOT NULL,
  llftnr integer NOT NULL,
  sibeh smallint NOT NULL,
  sizeile smallint NOT NULL,
  lzentposnr integer,
  stext text,
  sityp smallint NOT NULL,
  extracted_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  PRIMARY KEY (client_id, store_code, simarkt, laktnr, dartnr, llftnr, sibeh, sityp, sizeile)
);
COMMENT ON TABLE public.sigma_raw_dbadit IS 'Raw mirror of Sigma dw220sdb.DBAdit, every column (9), THE MIRROR RULE (SIGMA-SERVER-SCHEMA-MAP v1.7). Key = Sigma primary key. Loaded by Test-ExtractPromoOrderTables.ps1 until signed off.';
ALTER TABLE public.sigma_raw_dbadit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sigma_raw_dbadit FROM PUBLIC, anon, authenticated;
CREATE TRIGGER sigma_raw_dbadit_last_seen BEFORE INSERT OR UPDATE ON public.sigma_raw_dbadit FOR EACH ROW EXECUTE FUNCTION public.sigma_stamp_last_seen();

CREATE TABLE IF NOT EXISTS public.sigma_raw_dbaufk (
  client_id text NOT NULL DEFAULT 'socialbrand',
  store_code text NOT NULL,
  simktnr smallint NOT NULL,
  dauftrnr double precision NOT NULL,
  lliefnr integer,
  cvorart text,
  cstatu1 text,
  cstatu2 text,
  dtdatdis date,
  dtdatewe date,
  dtdatwe date,
  dtdatre date,
  dwenr double precision,
  crechnr text,
  dsumvk double precision,
  dsumek double precision,
  dsumvkp double precision,
  dsumekp double precision,
  dgutw double precision,
  drechw double precision,
  crabkz1 text,
  drab1 double precision,
  crabkz2 text,
  drab2 double precision,
  czustxt text,
  laktnr integer,
  csondva text,
  cumarkt text,
  sianzpos smallint,
  dtdatpr date,
  dtdatkond date,
  caktkz text,
  cspez text,
  dsummw double precision,
  siwaehrung smallint,
  sikpfand smallint,
  cweinfo text,
  tmzeitwe time,
  snamesped text,
  sianzbeh smallint,
  sianzkg double precision,
  sianzpal smallint,
  lanzart integer,
  sextbelnr text,
  sbediener text,
  czentaufnr text,
  cbelenr text,
  dwenrwe double precision,
  siposlautliefer smallint,
  csortber text,
  sihostorno smallint,
  dbarcodenr double precision,
  siweprotgedruckt smallint,
  dmessaufnr double precision,
  lvertreter integer,
  sibestgesendet smallint,
  lfibunummer integer,
  dtbearbbis date,
  sivorbestellung smallint,
  dtbestellbarab date,
  siinvers smallint,
  siregretgedruckt smallint,
  srefnr text,
  dtfaelligkeit date,
  cgutschriftnr text,
  sistatus smallint,
  dverknrech double precision,
  dreklamkolli double precision,
  sikopfpara smallint,
  sitransprechnen smallint,
  sizollstrechnen smallint,
  siabgleichohnetk smallint,
  dkurs double precision,
  sispeichneueeks smallint,
  extracted_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  PRIMARY KEY (client_id, store_code, simktnr, dauftrnr)
);
COMMENT ON TABLE public.sigma_raw_dbaufk IS 'Raw mirror of Sigma dw220sdb.DBAufK, every column (72), THE MIRROR RULE (SIGMA-SERVER-SCHEMA-MAP v1.7). Key = Sigma primary key. Loaded by Test-ExtractPromoOrderTables.ps1 until signed off.';
ALTER TABLE public.sigma_raw_dbaufk ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sigma_raw_dbaufk FROM PUBLIC, anon, authenticated;
CREATE TRIGGER sigma_raw_dbaufk_last_seen BEFORE INSERT OR UPDATE ON public.sigma_raw_dbaufk FOR EACH ROW EXECUTE FUNCTION public.sigma_stamp_last_seen();

CREATE TABLE IF NOT EXISTS public.sigma_raw_dbaufp (
  client_id text NOT NULL DEFAULT 'socialbrand',
  store_code text NOT NULL,
  simktnr smallint NOT NULL,
  dauftrnr double precision NOT NULL,
  lanrbest integer,
  dartnr double precision NOT NULL,
  cstatpos text,
  ckzvera text,
  dbemg double precision,
  sibeh smallint NOT NULL,
  ckzpos1 text,
  dwemg1 double precision,
  ckzpos2 text,
  dwemg2 double precision,
  ckzpos3 text,
  dwemg3 double precision,
  ckzpos4 text,
  dwemg4 double precision,
  dvk double precision,
  dek double precision,
  dekn double precision,
  dekwer double precision,
  dekweab double precision,
  dekwenn double precision,
  dmgwe double precision,
  lfolg integer NOT NULL,
  crabkz1 text,
  drab1 double precision,
  crabkz2 text,
  drab2 double precision,
  cspez text,
  dnmgwe double precision,
  caktkz text,
  laktnr integer,
  cbez text,
  sikzbez smallint,
  crueckst text,
  cnvenr text,
  dabwpfmg double precision,
  lliefnr integer,
  ceingabemg1 text,
  ceingabemg2 text,
  ceingabemg3 text,
  ceingabemg4 text,
  cfunkmde text,
  dartnrho double precision,
  dwemgze double precision,
  sinachlief smallint,
  sibestvormod smallint,
  cdiffgrund text,
  sinaenderbar smallint,
  siteilaufnr smallint,
  dekpf double precision,
  dekvorher double precision,
  lliefrechpos integer,
  drechekl double precision,
  drechekok double precision,
  drechmenge double precision,
  drechpossum double precision,
  sistatus smallint,
  drechekwer double precision,
  drechekwenn double precision,
  dreklwert double precision,
  sipospara smallint,
  drechrab double precision,
  simwst smallint,
  ckzstueck text,
  dvkalt double precision,
  dekwennextra double precision,
  dtdatmhd date,
  dtranspauf double precision,
  dzollstauf double precision,
  simittk smallint,
  dekwennfremd double precision,
  dreklwertohneextra double precision,
  lloadlist integer,
  caktek text,
  extracted_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  PRIMARY KEY (client_id, store_code, simktnr, dauftrnr, lfolg, dartnr, sibeh)
);
COMMENT ON TABLE public.sigma_raw_dbaufp IS 'Raw mirror of Sigma dw220sdb.DBAufP, every column (75), THE MIRROR RULE (SIGMA-SERVER-SCHEMA-MAP v1.7). Key = Sigma primary key. Loaded by Test-ExtractPromoOrderTables.ps1 until signed off.';
ALTER TABLE public.sigma_raw_dbaufp ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sigma_raw_dbaufp FROM PUBLIC, anon, authenticated;
CREATE TRIGGER sigma_raw_dbaufp_last_seen BEFORE INSERT OR UPDATE ON public.sigma_raw_dbaufp FOR EACH ROW EXECUTE FUNCTION public.sigma_stamp_last_seen();

CREATE TABLE IF NOT EXISTS public.sigma_raw_intellistox_promo (
  client_id text NOT NULL DEFAULT 'socialbrand',
  store_code text NOT NULL,
  capture_date date NOT NULL,
  uid bigint NOT NULL,
  productcode double precision,
  promosupplier integer,
  promonumber integer,
  nationalnumber text,
  fromdate date,
  todate date,
  active boolean,
  cebene text,
  normalprice double precision,
  normalvat double precision,
  normalpackcost double precision,
  normalpacksize smallint,
  normalgp double precision,
  normalgp_pct text,
  promoprice double precision,
  promovat double precision,
  promopackcost double precision,
  promopacksize smallint,
  costdiff_pct text,
  promogp double precision,
  promogp_pct text,
  dtlieftag1 date,
  dtlieftag2 date,
  cbez text,
  ckdkz6 text,
  daktmengewo1 double precision,
  daktmengewo1datum date,
  daktmengewo2 double precision,
  daktmengewo2datum date,
  daktmengewo3 double precision,
  daktmengewo3datum date,
  daktmengewo4 double precision,
  daktmengewo4datum date,
  daktmengewo5 double precision,
  daktmengewo5datum date,
  daktmengewo6 double precision,
  daktmengewo6datum date,
  extracted_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  PRIMARY KEY (client_id, store_code, capture_date, uid)
);
COMMENT ON TABLE public.sigma_raw_intellistox_promo IS 'Raw mirror of Sigma EASYDB.IntellistoX_Promo_Info_Master, every column (38), THE MIRROR RULE (SIGMA-SERVER-SCHEMA-MAP v1.7). Key = Sigma primary key plus capture_date (nightly snapshot). Loaded by Test-ExtractPromoOrderTables.ps1 until signed off.';
ALTER TABLE public.sigma_raw_intellistox_promo ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sigma_raw_intellistox_promo FROM PUBLIC, anon, authenticated;
CREATE TRIGGER sigma_raw_intellistox_promo_last_seen BEFORE INSERT OR UPDATE ON public.sigma_raw_intellistox_promo FOR EACH ROW EXECUTE FUNCTION public.sigma_stamp_last_seen();
